// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDueT-OtEy7zwSYF4kIx3kyZwNDKDycpTU',
    appId: '1:309983931368:web:509aa3b7eeb016d66c125d',
    messagingSenderId: '309983931368',
    projectId: 'tansen-music-418e5',
    authDomain: 'tansen-music-418e5.firebaseapp.com',
    storageBucket: 'tansen-music-418e5.appspot.com',
    measurementId: 'G-RQ580EYG9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdh9I5monT3NIbZP2fcKnxI1GVBz2bzI',
    appId: '1:309983931368:android:5e62bf076ae1045f6c125d',
    messagingSenderId: '309983931368',
    projectId: 'tansen-music-418e5',
    storageBucket: 'tansen-music-418e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojl_7M3LAyS6qvKPdlzn1CdGOzjm9mDo',
    appId: '1:309983931368:ios:80cf297f73c9ae356c125d',
    messagingSenderId: '309983931368',
    projectId: 'tansen-music-418e5',
    storageBucket: 'tansen-music-418e5.appspot.com',
    iosBundleId: 'tansen.music.tansen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojl_7M3LAyS6qvKPdlzn1CdGOzjm9mDo',
    appId: '1:309983931368:ios:7a8775e38def53eb6c125d',
    messagingSenderId: '309983931368',
    projectId: 'tansen-music-418e5',
    storageBucket: 'tansen-music-418e5.appspot.com',
    iosBundleId: 'tansen.music.tansen.RunnerTests',
  );
}
